name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Build and Test Backend
        run: ./gradlew clean test build --info --no-daemon
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            --build-arg API_KEY=${{ secrets.API_KEY }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg ADMIN_SECRET=${{ secrets.ADMIN_SECRET }} \
            -t webserviceproject:latest .

      - name: Run Tests with Docker Image
        run: |
          docker run --rm -d \
            -e SPRING_PROFILES_ACTIVE=test \
            -e DATABASE_URL=jdbc:h2:mem:testdb \
            -e DATABASE_USERNAME=sa \
            -e DATABASE_PASSWORD=password \
            -p 8443:8443 webserviceproject:latest
